//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/dev/Downloads/EnFuck/src/main/java/com/flipper/enparse\EnforceParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
namespace PakExplorer.Es.Antlr; 

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EnforceParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IEnforceParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.computationalUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComputationalUnit([NotNull] EnforceParser.ComputationalUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.computationalUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComputationalUnit([NotNull] EnforceParser.ComputationalUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableModifier([NotNull] EnforceParser.VariableModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableModifier([NotNull] EnforceParser.VariableModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodModifier([NotNull] EnforceParser.MethodModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodModifier([NotNull] EnforceParser.MethodModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterModifier([NotNull] EnforceParser.ParameterModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterModifier([NotNull] EnforceParser.ParameterModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassModifier([NotNull] EnforceParser.ClassModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassModifier([NotNull] EnforceParser.ClassModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalDeclaration([NotNull] EnforceParser.GlobalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalDeclaration([NotNull] EnforceParser.GlobalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] EnforceParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] EnforceParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classOrEnumExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrEnumExtension([NotNull] EnforceParser.ClassOrEnumExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classOrEnumExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrEnumExtension([NotNull] EnforceParser.ClassOrEnumExtensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameters([NotNull] EnforceParser.TypeParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameters([NotNull] EnforceParser.TypeParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] EnforceParser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] EnforceParser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] EnforceParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] EnforceParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] EnforceParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] EnforceParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValue([NotNull] EnforceParser.EnumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValue([NotNull] EnforceParser.EnumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] EnforceParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] EnforceParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] EnforceParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] EnforceParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] EnforceParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] EnforceParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] EnforceParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] EnforceParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodBody([NotNull] EnforceParser.MethodBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodBody([NotNull] EnforceParser.MethodBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeTypeOrVoid([NotNull] EnforceParser.TypeTypeOrVoidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeTypeOrVoid([NotNull] EnforceParser.TypeTypeOrVoidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] EnforceParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] EnforceParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarators([NotNull] EnforceParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarators([NotNull] EnforceParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] EnforceParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] EnforceParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorId([NotNull] EnforceParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorId([NotNull] EnforceParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] EnforceParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] EnforceParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterList([NotNull] EnforceParser.FormalParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterList([NotNull] EnforceParser.FormalParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] EnforceParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] EnforceParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterUndefined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterUndefined([NotNull] EnforceParser.FormalParameterUndefinedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterUndefined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterUndefined([NotNull] EnforceParser.FormalParameterUndefinedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterDefined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterDefined([NotNull] EnforceParser.FormalParameterDefinedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterDefined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterDefined([NotNull] EnforceParser.FormalParameterDefinedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializer([NotNull] EnforceParser.VariableInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializer([NotNull] EnforceParser.VariableInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInitializer([NotNull] EnforceParser.ArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInitializer([NotNull] EnforceParser.ArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] EnforceParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] EnforceParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralBoolean([NotNull] EnforceParser.LiteralBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralBoolean([NotNull] EnforceParser.LiteralBooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralString([NotNull] EnforceParser.LiteralStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralString([NotNull] EnforceParser.LiteralStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralNull([NotNull] EnforceParser.LiteralNullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralNull([NotNull] EnforceParser.LiteralNullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalNumeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralNumeric([NotNull] EnforceParser.LiteralNumericContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalNumeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralNumeric([NotNull] EnforceParser.LiteralNumericContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalFloat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralFloat([NotNull] EnforceParser.LiteralFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalFloat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralFloat([NotNull] EnforceParser.LiteralFloatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralInteger([NotNull] EnforceParser.LiteralIntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralInteger([NotNull] EnforceParser.LiteralIntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalVector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralVector([NotNull] EnforceParser.LiteralVectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalVector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralVector([NotNull] EnforceParser.LiteralVectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassType([NotNull] EnforceParser.ClassTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassType([NotNull] EnforceParser.ClassTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] EnforceParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] EnforceParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] EnforceParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] EnforceParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] EnforceParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] EnforceParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.deleteStatment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteStatment([NotNull] EnforceParser.DeleteStatmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.deleteStatment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteStatment([NotNull] EnforceParser.DeleteStatmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.threadStatment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThreadStatment([NotNull] EnforceParser.ThreadStatmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.threadStatment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThreadStatment([NotNull] EnforceParser.ThreadStatmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] EnforceParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] EnforceParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] EnforceParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] EnforceParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] EnforceParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] EnforceParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachStatement([NotNull] EnforceParser.ForeachStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachStatement([NotNull] EnforceParser.ForeachStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] EnforceParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] EnforceParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] EnforceParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] EnforceParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlockStatementGroup([NotNull] EnforceParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlockStatementGroup([NotNull] EnforceParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabel([NotNull] EnforceParser.SwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabel([NotNull] EnforceParser.SwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForControl([NotNull] EnforceParser.ForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForControl([NotNull] EnforceParser.ForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] EnforceParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] EnforceParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachControl([NotNull] EnforceParser.ForeachControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachControl([NotNull] EnforceParser.ForeachControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forEachVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachVariableList([NotNull] EnforceParser.ForEachVariableListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forEachVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachVariableList([NotNull] EnforceParser.ForEachVariableListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forEachVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachVariable([NotNull] EnforceParser.ForEachVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forEachVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachVariable([NotNull] EnforceParser.ForEachVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclaration([NotNull] EnforceParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclaration([NotNull] EnforceParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclarationRegular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclarationRegular([NotNull] EnforceParser.LocalVariableDeclarationRegularContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclarationRegular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclarationRegular([NotNull] EnforceParser.LocalVariableDeclarationRegularContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclarationAssumptuative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclarationAssumptuative([NotNull] EnforceParser.LocalVariableDeclarationAssumptuativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclarationAssumptuative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclarationAssumptuative([NotNull] EnforceParser.LocalVariableDeclarationAssumptuativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] EnforceParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] EnforceParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParExpression([NotNull] EnforceParser.ParExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParExpression([NotNull] EnforceParser.ParExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] EnforceParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] EnforceParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.specificParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecificParam([NotNull] EnforceParser.SpecificParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.specificParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecificParam([NotNull] EnforceParser.SpecificParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] EnforceParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] EnforceParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] EnforceParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] EnforceParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] EnforceParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] EnforceParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] EnforceParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] EnforceParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreator([NotNull] EnforceParser.CreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreator([NotNull] EnforceParser.CreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatedName([NotNull] EnforceParser.CreatedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatedName([NotNull] EnforceParser.CreatedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.innerCreator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInnerCreator([NotNull] EnforceParser.InnerCreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.innerCreator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInnerCreator([NotNull] EnforceParser.InnerCreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayCreatorRest([NotNull] EnforceParser.ArrayCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayCreatorRest([NotNull] EnforceParser.ArrayCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassCreatorRest([NotNull] EnforceParser.ClassCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassCreatorRest([NotNull] EnforceParser.ClassCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.explicitGenericInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitGenericInvocation([NotNull] EnforceParser.ExplicitGenericInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.explicitGenericInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitGenericInvocation([NotNull] EnforceParser.ExplicitGenericInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgumentsOrDiamond([NotNull] EnforceParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgumentsOrDiamond([NotNull] EnforceParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonWildcardTypeArgumentsOrDiamond([NotNull] EnforceParser.NonWildcardTypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonWildcardTypeArgumentsOrDiamond([NotNull] EnforceParser.NonWildcardTypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonWildcardTypeArguments([NotNull] EnforceParser.NonWildcardTypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonWildcardTypeArguments([NotNull] EnforceParser.NonWildcardTypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] EnforceParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] EnforceParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeListChild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeListChild([NotNull] EnforceParser.TypeListChildContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeListChild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeListChild([NotNull] EnforceParser.TypeListChildContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeType([NotNull] EnforceParser.TypeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeType([NotNull] EnforceParser.TypeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] EnforceParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] EnforceParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArguments([NotNull] EnforceParser.TypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArguments([NotNull] EnforceParser.TypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgument([NotNull] EnforceParser.TypeArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgument([NotNull] EnforceParser.TypeArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperSuffix([NotNull] EnforceParser.SuperSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperSuffix([NotNull] EnforceParser.SuperSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitGenericInvocationSuffix([NotNull] EnforceParser.ExplicitGenericInvocationSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitGenericInvocationSuffix([NotNull] EnforceParser.ExplicitGenericInvocationSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] EnforceParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] EnforceParser.ArgumentsContext context);
}
