//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/dev/Downloads/EnFuck/src/main/java/com/flipper/enparse\EnforceParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
namespace PakExplorer.Es.Antlr; 


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEnforceParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EnforceParserBaseListener : IEnforceParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.computationalUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputationalUnit([NotNull] EnforceParser.ComputationalUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.computationalUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputationalUnit([NotNull] EnforceParser.ComputationalUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifier([NotNull] EnforceParser.VariableModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifier([NotNull] EnforceParser.VariableModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodModifier([NotNull] EnforceParser.MethodModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodModifier([NotNull] EnforceParser.MethodModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parameterModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterModifier([NotNull] EnforceParser.ParameterModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parameterModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterModifier([NotNull] EnforceParser.ParameterModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassModifier([NotNull] EnforceParser.ClassModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassModifier([NotNull] EnforceParser.ClassModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalDeclaration([NotNull] EnforceParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalDeclaration([NotNull] EnforceParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] EnforceParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] EnforceParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classOrEnumExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrEnumExtension([NotNull] EnforceParser.ClassOrEnumExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classOrEnumExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrEnumExtension([NotNull] EnforceParser.ClassOrEnumExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameters([NotNull] EnforceParser.TypeParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameters([NotNull] EnforceParser.TypeParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameter([NotNull] EnforceParser.TypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameter([NotNull] EnforceParser.TypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] EnforceParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] EnforceParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] EnforceParser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] EnforceParser.EnumBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] EnforceParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] EnforceParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] EnforceParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] EnforceParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] EnforceParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] EnforceParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] EnforceParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] EnforceParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] EnforceParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] EnforceParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] EnforceParser.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] EnforceParser.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeTypeOrVoid([NotNull] EnforceParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeTypeOrVoid([NotNull] EnforceParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] EnforceParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] EnforceParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarators([NotNull] EnforceParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarators([NotNull] EnforceParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] EnforceParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] EnforceParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] EnforceParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] EnforceParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] EnforceParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] EnforceParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] EnforceParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] EnforceParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] EnforceParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] EnforceParser.FormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterUndefined"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterUndefined([NotNull] EnforceParser.FormalParameterUndefinedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterUndefined"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterUndefined([NotNull] EnforceParser.FormalParameterUndefinedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.formalParameterDefined"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterDefined([NotNull] EnforceParser.FormalParameterDefinedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.formalParameterDefined"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterDefined([NotNull] EnforceParser.FormalParameterDefinedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializer([NotNull] EnforceParser.VariableInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializer([NotNull] EnforceParser.VariableInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInitializer([NotNull] EnforceParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInitializer([NotNull] EnforceParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] EnforceParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] EnforceParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralBoolean([NotNull] EnforceParser.LiteralBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralBoolean([NotNull] EnforceParser.LiteralBooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralString([NotNull] EnforceParser.LiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralString([NotNull] EnforceParser.LiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralNull([NotNull] EnforceParser.LiteralNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralNull([NotNull] EnforceParser.LiteralNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralNumeric([NotNull] EnforceParser.LiteralNumericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralNumeric([NotNull] EnforceParser.LiteralNumericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralFloat([NotNull] EnforceParser.LiteralFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralFloat([NotNull] EnforceParser.LiteralFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralInteger([NotNull] EnforceParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralInteger([NotNull] EnforceParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.literalVector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralVector([NotNull] EnforceParser.LiteralVectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.literalVector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralVector([NotNull] EnforceParser.LiteralVectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassType([NotNull] EnforceParser.ClassTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassType([NotNull] EnforceParser.ClassTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] EnforceParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] EnforceParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] EnforceParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] EnforceParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] EnforceParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] EnforceParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.deleteStatment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteStatment([NotNull] EnforceParser.DeleteStatmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.deleteStatment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteStatment([NotNull] EnforceParser.DeleteStatmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.threadStatment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThreadStatment([NotNull] EnforceParser.ThreadStatmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.threadStatment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThreadStatment([NotNull] EnforceParser.ThreadStatmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] EnforceParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] EnforceParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] EnforceParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] EnforceParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] EnforceParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] EnforceParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.foreachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachStatement([NotNull] EnforceParser.ForeachStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.foreachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachStatement([NotNull] EnforceParser.ForeachStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] EnforceParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] EnforceParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] EnforceParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] EnforceParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlockStatementGroup([NotNull] EnforceParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlockStatementGroup([NotNull] EnforceParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabel([NotNull] EnforceParser.SwitchLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabel([NotNull] EnforceParser.SwitchLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForControl([NotNull] EnforceParser.ForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForControl([NotNull] EnforceParser.ForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInit([NotNull] EnforceParser.ForInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInit([NotNull] EnforceParser.ForInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.foreachControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachControl([NotNull] EnforceParser.ForeachControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.foreachControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachControl([NotNull] EnforceParser.ForeachControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forEachVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForEachVariableList([NotNull] EnforceParser.ForEachVariableListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forEachVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForEachVariableList([NotNull] EnforceParser.ForEachVariableListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.forEachVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForEachVariable([NotNull] EnforceParser.ForEachVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.forEachVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForEachVariable([NotNull] EnforceParser.ForEachVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] EnforceParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] EnforceParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclarationRegular"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclarationRegular([NotNull] EnforceParser.LocalVariableDeclarationRegularContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclarationRegular"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclarationRegular([NotNull] EnforceParser.LocalVariableDeclarationRegularContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.localVariableDeclarationAssumptuative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclarationAssumptuative([NotNull] EnforceParser.LocalVariableDeclarationAssumptuativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.localVariableDeclarationAssumptuative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclarationAssumptuative([NotNull] EnforceParser.LocalVariableDeclarationAssumptuativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] EnforceParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] EnforceParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpression([NotNull] EnforceParser.ParExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpression([NotNull] EnforceParser.ParExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] EnforceParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] EnforceParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.specificParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecificParam([NotNull] EnforceParser.SpecificParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.specificParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecificParam([NotNull] EnforceParser.SpecificParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] EnforceParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] EnforceParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] EnforceParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] EnforceParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] EnforceParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] EnforceParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] EnforceParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] EnforceParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] EnforceParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] EnforceParser.CreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] EnforceParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] EnforceParser.CreatedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInnerCreator([NotNull] EnforceParser.InnerCreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInnerCreator([NotNull] EnforceParser.InnerCreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayCreatorRest([NotNull] EnforceParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayCreatorRest([NotNull] EnforceParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] EnforceParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] EnforceParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocation([NotNull] EnforceParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocation([NotNull] EnforceParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgumentsOrDiamond([NotNull] EnforceParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgumentsOrDiamond([NotNull] EnforceParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArgumentsOrDiamond([NotNull] EnforceParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArgumentsOrDiamond([NotNull] EnforceParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArguments([NotNull] EnforceParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArguments([NotNull] EnforceParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeList([NotNull] EnforceParser.TypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeList([NotNull] EnforceParser.TypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeListChild"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeListChild([NotNull] EnforceParser.TypeListChildContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeListChild"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeListChild([NotNull] EnforceParser.TypeListChildContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeType([NotNull] EnforceParser.TypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeType([NotNull] EnforceParser.TypeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] EnforceParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] EnforceParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] EnforceParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] EnforceParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgument([NotNull] EnforceParser.TypeArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgument([NotNull] EnforceParser.TypeArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperSuffix([NotNull] EnforceParser.SuperSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperSuffix([NotNull] EnforceParser.SuperSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocationSuffix([NotNull] EnforceParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocationSuffix([NotNull] EnforceParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnforceParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] EnforceParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnforceParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] EnforceParser.ArgumentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}